/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class OpenLipcJNI {
  public final static native int LipcOpenEx(String jarg1, long jarg2);
  public final static native int LipcOpen(String jarg1);
  public final static native int LipcOpenNoName();
  public final static native int LipcClose(int jarg1);
  public final static native int LipcSetStringProperty(int jarg1, String jarg2, String jarg3, String jarg4);
  public final static native int LipcSetIntProperty(int jarg1, String jarg2, String jarg3, int jarg4);
  public final static native int LipcGetStringProperty(int jarg1, String jarg2, String jarg3, long jarg4);
  public final static native int LipcGetIntProperty(int jarg1, String jarg2, String jarg3, long jarg4);
  public final static native void LipcFreeString(String jarg1);
  public final static native String LipcGetErrorString(int jarg1);
  public final static native int LipcNewEvent(int jarg1, String jarg2);
  public final static native int LipcAddIntParam(int jarg1, int jarg2);
  public final static native int LipcAddStringParam(int jarg1, String jarg2);
  public final static native int LipcSendEvent(int jarg1, int jarg2);
  public final static native int LipcEventFree(int jarg1);
}
