/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class OpenLipc {
  public static int LipcOpenEx(String source, SWIGTYPE_p_int lipc_status) {
    return OpenLipcJNI.LipcOpenEx(source, SWIGTYPE_p_int.getCPtr(lipc_status));
  }

  public static int LipcOpen(String source) {
    return OpenLipcJNI.LipcOpen(source);
  }

  public static int LipcOpenNoName() {
    return OpenLipcJNI.LipcOpenNoName();
  }

  public static int LipcClose(int lipc_handle) {
    return OpenLipcJNI.LipcClose(lipc_handle);
  }

  public static int LipcSetStringProperty(int lipc_handle, String publisher, String property, String value) {
    return OpenLipcJNI.LipcSetStringProperty(lipc_handle, publisher, property, value);
  }

  public static int LipcSetIntProperty(int lipc_handle, String publisher, String property, int value) {
    return OpenLipcJNI.LipcSetIntProperty(lipc_handle, publisher, property, value);
  }

  public static int LipcGetStringProperty(int lipc_handle, String publisher, String property, SWIGTYPE_p_p_char value) {
    return OpenLipcJNI.LipcGetStringProperty(lipc_handle, publisher, property, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public static int LipcGetIntProperty(int lipc_handle, String publisher, String property, SWIGTYPE_p_int value) {
    return OpenLipcJNI.LipcGetIntProperty(lipc_handle, publisher, property, SWIGTYPE_p_int.getCPtr(value));
  }

  public static void LipcFreeString(String string) {
    OpenLipcJNI.LipcFreeString(string);
  }

  public static String LipcGetErrorString(int error) {
    return OpenLipcJNI.LipcGetErrorString(error);
  }

  public static int LipcNewEvent(int lipc_handle, String event_name) {
    return OpenLipcJNI.LipcNewEvent(lipc_handle, event_name);
  }

  public static int LipcAddIntParam(int event_handle, int value) {
    return OpenLipcJNI.LipcAddIntParam(event_handle, value);
  }

  public static int LipcAddStringParam(int event_handle, String value) {
    return OpenLipcJNI.LipcAddStringParam(event_handle, value);
  }

  public static int LipcSendEvent(int lipc_handle, int event_handle) {
    return OpenLipcJNI.LipcSendEvent(lipc_handle, event_handle);
  }

  public static int LipcEventFree(int event_handle) {
    return OpenLipcJNI.LipcEventFree(event_handle);
  }

}
